openfga/language

.gitattributes, pkg/go/Makefile, pkg/go/gen/openfga_base_listener.go, pkg/go/gen/openfga_lexer.go, pkg/go/gen/openfga_listener.go, pkg/go/gen/openfga_parser.go, pkg/go/go.mod, pkg/go/go.sum, pkg/go/transformer/dsltojson.go, pkg/go/transformer/dsltojson_test.go, pkg/go/transformer/jsontodsl.go, pkg/go/transformer/jsontodsl_test.go, pkg/go/transformer/testcases_test.go, pkg/js/transformer/_testcases.ts, pkg/js/transformer/dsltojson.test.ts, pkg/js/transformer/dsltojson.ts, pkg/js/transformer/jsontodsl.test.ts, tests/data/dsl-syntax-validation.json
- closes #9 
- https://www.antlr.org/api/Java/org/antlr/v4/runtime/ANTLRErrorListener.html
- https://stackoverflow.com/questions/18132078/handling-errors-in-antlr4?rq=4
- https://stackoverflow.com/questions/20828864/accumulating-collecting-errors-via-errorlistener-to-handle-after-the-parse
=> feat: throw error on invalid syntax

pkg/js/package-lock.json, pkg/js/package.json, pkg/js/transformer/_testcases.ts
* Replaced `js-yaml` with more recently maintained `yaml`.
* Updated test suite accordingly.
=> chore: replace js-yaml with yaml

pkg/js/transformer/dsltojson.test.ts, tests/data/dsl-syntax-validation-cases.yaml
* Updated tests with invalid syntax to have expected error message.
* Associated with change issue https://github.com/openfga/language/issues/30
=> fix: Added correct failure messages to existing, failing tests

pkg/js/transformer/_testcases.ts, pkg/js/transformer/dsltojson.test.ts, pkg/js/transformer/dsltojson.ts, pkg/js/validator/validate-dsl.test.ts, pkg/js/validator/validate-dsl.ts, tests/data/dsl-syntax-validation-cases.yaml
* Refactored `transformDslToJSON` to share code
* Updated test suite for additional expect verification with expected test case content
* Updated test data to list out an array of expected errors from lexer / parser.
* Addresses https://github.com/openfga/language/issues/30 for existing, working cases
=> feat: Adding validateDsl and adapt tests

pkg/js/transformer/dsltojson.ts, tests/data/dsl-syntax-validation-cases.yaml
Fix for null pointer when define was misspelled.
=> fix: address and test misspelled define

pkg/js/errors.ts, pkg/js/transformer/_testcases.ts, pkg/js/transformer/dsltojson.ts, pkg/js/util/exceptions.ts, pkg/js/validator/Keywords.ts, pkg/js/validator/validate-dsl.test.ts, pkg/js/validator/validate-dsl.ts, tests/data/dsl-syntax-validation-cases.yaml, tests/data/dsl-validation-cases.yaml
Rough first cut for any feedback.
=> feat: Validation of DSL

pkg/js/.eslintrc.js, pkg/js/errors.ts, pkg/js/transformer/dsltojson.test.ts, pkg/js/util/exceptions.ts, pkg/js/validator/Keywords.ts, pkg/js/validator/validate-dsl.test.ts, pkg/js/validator/validate-dsl.ts
* Added rule for trailing spaces
* Auto-fix all trailing spaces
=> chore: Remove trailing spaces

pkg/js/errors.ts
Adding accessors to BaseError that take an offset.
=> feat: Adding line & column getters with offset

.github/workflows/main-js.yaml, pkg/js/errors.ts, pkg/js/jest.config.js, pkg/js/tsconfig.json
* Exposed by syntax-transformer, this PR fixes  formatting errors raised
* audit, lint & prettier added and passing now
=> fix: prettier fixes exposed on build of syntax-transformer

pkg/js/transformer/dsltojson.ts, tests/data/dsl-syntax-validation-cases.yaml
Poorly formatted DSL was causing a TypeError, failing to get the TypeDef name text.
=> fix: Type Error for poorly formatted DSL

pkg/js/index.ts
Exporting validation interface for use in syntax-transformer
=> chore: exporting validateDsl function and error objects

pkg/js/package-lock.json, pkg/js/package.json
=> feat: publish as @openfga/syntax-transformer

pkg/js/validator/validate-dsl.ts, tests/data/dsl-semantic-validation-cases.yaml
* Swap precedence for duplicate check
* Added test case for this change
=> fix: Rule precedence for duplicates

pkg/go/go.mod, pkg/go/transformer/dsltojson.go
=> fix(go): fix position thrown on dup location

pkg/go/transformer/dsltojson.go, pkg/go/transformer/dsltojson_test.go, pkg/js/tests/dsltojson.test.ts, pkg/js/transformer/dsltojson.ts
=> feat!: add transform to proto and must transform

Makefile
=> chore: cleanup make file (allow using podman instead of docker)

.github/workflows/main-go.yaml, .github/workflows/main-js.yaml, README.md, pkg/js/CHANGELOG.md, pkg/js/package-lock.json, pkg/js/package.json, pkg/js/validator/validate-dsl.ts, tests/data/dsl-syntax-validation-cases.yaml
- closes https://github.com/openfga/language/issues/120
=> fix: resolve issue with improperly detecting a valid model as invalid

pkg/go/transformer/jsontodsl.go, pkg/js/transformer/jsontodsl.ts
Refactor JSON to DSL validator to not use a global direct assignment validator instance.
As discussed with @rhamzeh and in #136, we don't need to have a global direct assignment validator instance in the JSON to DSL transformers. This change removes the global instance and instead creates an instance in `parseRelation`, which removes the need for the `reset()` method. It also removes some unused code in the validator for the `stateStack`.
- #136 
- #107
=> chore: remove global validator from JSON to DSL transform.

pkg/js/errors.ts, pkg/js/tests/_testcases.ts, pkg/js/tests/validator.test.ts, pkg/js/util/exceptions.ts, pkg/js/validator/validate-dsl.ts, tests/data/json-validation-cases.yaml
- resolves https://github.com/openfga/language/issues/100
=> feat: Validation for JSON models

pkg/js/errors.ts, pkg/js/tests/modules/module-to-model.test.ts, pkg/js/transformer/modules/modules-to-model.ts, pkg/js/util/exceptions.ts, pkg/js/validator/validate-dsl.ts, tests/data/transformer-module/01-module-with-errors/expected_errors.json, tests/data/transformer-module/01-module-with-errors/module/core.fga
This is a start on mapping the errors raised during a modular transform back to their original source files, it's only a limited set right now but starts the basis of how we could do this.
Given we don't have validation in the Go package yet I'm not really sure what we can do to support those there :/
Start of #186
=> feat(js): improve some reported errors from validating final model in modular transform

README.md
* Update js installation instructions
* Add Java description
=> chore(docs): update java status in readme

pkg/js/CHANGELOG.md, pkg/js/package-lock.json, pkg/js/package.json
=> release(js): v0.2.0-beta.13

pkg/js/errors.ts, pkg/js/transformer/modules/modules-to-model.ts, pkg/js/util/exceptions.ts, pkg/js/validator/validate-dsl.ts, tests/data/dsl-semantic-validation-cases.yaml, tests/data/transformer-module/05-module-with-relation-errors/expected_errors.json, tests/data/transformer-module/05-module-with-relation-errors/module/employee.fga
Can be replicated with given module
```
module employee
type employe
relations
define can_manage: manager or can_manage from manager
define manager: [employee]
```
Working
=> fix: Missing metadata on invalid-relation-type

.github/CODEOWNERS
=> chore: allow dx to approve readme changes

pkg/js/CHANGELOG.md, pkg/js/package-lock.json, pkg/js/package.json, pkg/js/util/exceptions.ts, tests/data/dsl-semantic-validation-cases.yaml
=> fix: incorrect range for 'condition-not-defined'

Makefile, tests/data/dsl-semantic-validation-cases.yaml
Adds more tests to cover single character types, relations, and conditions. There are 2 that currently aren't covered as I can't find any reference to the errors currently.
* "assignable-relation-must-have-type"
* "type-wildcard-relation"
=> test: add more tests for single letter types, relations, and conditions

pkg/js/CHANGELOG.md, pkg/js/package-lock.json, pkg/js/package.json
=> release: v0.2.0-beta.16

.github/dependabot.yaml, .github/workflows/main-go.yaml, .github/workflows/main-java.yml, pkg/go/transformer/mod-to-json.go, pkg/js/package-lock.json, pkg/js/transformer/modules/mod-to-json.ts, pkg/js/transformer/modules/modules-to-model.ts, pkg/js/validator/validate-dsl.ts, tests/data/fga-mod-transformer-cases.yaml
This PR fixes a vulnerability in the YAML content validation process. The changes ensure that paths containing `../` are not allowed, preventing directory traversal attacks.
fixes #199
=> Prevent Directory Traversal in YAML Content Validation

pkg/js/transformer/dsltojson.ts, tests/data/dsl-syntax-validation-cases.yaml
* Easiest way to deal with this is with a generic syntax error
* Added its own test data package due to syntax errors causing a parsing halt
=> fix: syntax error for missing module name

pkg/js/CHANGELOG.md
=> release(js): v0.2.0-beta.17

pkg/js/package-lock.json, pkg/js/package.json
=> release: bump pkg for v0.2.0-beta.17

.github/workflows/main-js.yaml
This pull request fixes the CI pipeline by using pinned dependencies for better security. It also updates the Docker Buildx setup.
=> fix(ci): Use pinned dependencies for better security

pkg/java/src/main/java/dev/openfga/language/validation/Dsl.java, pkg/js/errors.ts, pkg/js/transformer/modules/modules-to-model.ts, pkg/js/util/exceptions.ts, pkg/js/util/line-numbers.ts, pkg/js/validator/validate-dsl.ts, tests/data/dsl-semantic-validation-cases.yaml
- fixes https://github.com/openfga/language/issues/255
=> fix: incorrectly assigned error

.github/workflows/pkg-go-pr.yaml, .github/workflows/pkg-java-pr.yaml, .github/workflows/pkg-js-pr.yaml
=> fix: add push on main branch to PRs

.github/workflows/pkg-js-release.yaml
=> fix: specify location of package-lock.json

.github/workflows/pkg-js-release.yaml, pkg/js/package-lock.json, pkg/js/package.json
=> chore(js): fix release

pkg/java/settings.gradle
=> fix: set name of rootProject

.github/workflows/pkg-java-release.yaml, pkg/java/CHANGELOG.md, pkg/java/publish.gradle
=> release(java): v0.2.0-beta.1

pkg/js/tests/validate-rules.test.ts, pkg/js/validator/index.ts, pkg/js/validator/validate-store.ts
=> fix: instancePath using incorrect value for tests

pkg/js/CHANGELOG.md, pkg/js/package-lock.json, pkg/js/package.json
=> release(js): v0.2.0-beta.19

pkg/go/.golangci.yaml, pkg/go/Makefile, pkg/go/graph/graph_builder.go, pkg/go/graph/graph_builder_test.go
Follow-up of https://github.com/openfga/language/pull/307.
I'm building this incrementally. More PRs will follow.
=> feat: support direct assignments in graph

pkg/go/.golangci.yaml, pkg/go/graph/graph_builder.go, pkg/go/validation/validation-rules_test.go
=> Refactor graph

pkg/js/package-lock.json, pkg/js/package.json
=> chore(js): update deps

pkg/go/validation/validation-rules.go, pkg/java/src/main/java/dev/openfga/language/validation/Validator.java, pkg/js/validator/validate-rules.ts
Restrict character limit of condition and condition references down to 50 characters. Updated java, go & js regexs.
https://github.com/openfga/language/issues/319
=> fix: restrict condition name to 50 characters

pkg/go/graph/graph_builder.go, pkg/go/graph/graph_builder_test.go
=> feat: deduplicate direct assignments with conditions in graph

pkg/go/graph/graph_builder.go, pkg/go/graph/graph_builder_test.go
=> feat: basic support for exclusion in graph

pkg/go/graph/graph_builder_test.go
Reviewers: please read every model in this folder, https://github.com/openfga/language/tree/main/tests/data/transformer and then use https://dreampuf.github.io/GraphvizOnline/ to visualize the graph to confirm that it's what you expect.
=> test: add graph tests for recursive models

pkg/go/graph/graph.go, pkg/go/graph/graph_builder_test.go
Add cycle detection in go graph library.  This serves as future starting point for performance optimization in OpenFGA server.
=> feat: add cycle detection

pkg/go/graph/graph.go, pkg/go/graph/graph_builder.go, pkg/go/graph/graph_test.go
Add helper methods as required by https://github.com/openfga/openfga/pull/1946
=> feat: expose graph methods

pkg/js/CHANGELOG.md, pkg/js/package-lock.json, pkg/js/package.json
=> release(js): v0.2.0-beta.22

pkg/go/graph/weighted_graph.go, pkg/go/graph/weighted_graph_edge.go, pkg/go/graph/weighted_graph_node.go, pkg/go/graph/weighted_graph_test.go, pkg/go/transformer/dsltojson_test.go, pkg/go/transformer/jsontodsl.go, pkg/go/transformer/module-to-model_test.go
adding getters to weighted graph, node and edges to be able to be used in the algorithms
adding getters to weighted graph, node and edges to be able to be used in the algorithms
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)
=> adding getters to weighted graph

pkg/go/graph/weighted_graph.go, pkg/go/graph/weighted_graph_edge.go, pkg/go/graph/weighted_graph_node.go
To improve the developer experience.
- Rename `GetEdgesByNode` to `GetEdgesFromNode` ⚠️ this is a minor breaking change.
- Update godocs
=> chore: rename methods for clarity and improve godocs of model graph

.github/workflows/scorecard.yml
=> chore: create scorecard.yml
