openfga/language

pkg/js/package.json

When used as a submodule, eslint detects multiple eslint configs and fails out. Explicitly set location of config.

fix: specify eslint config file to avoid duplication error

---

pkg/js/tests/validator.test.ts
pkg/js/transformer/dsltojson.ts
tests/data/dsl-syntax-validation-cases.yaml

Fixing bug where <EOF> was being elected as the offending token.
This has been changed to be the relationName.

fix: duplicate exception

---

pkg/js/CHANGELOG.md
pkg/js/package-lock.json
pkg/js/package.json

Release `syntax-transformer@v0.2.0-beta.2` for use in the VS Code extension

release(js): syntax-transformer@v0.2.0-beta.2

---

pkg/go/go.mod

Bump go version
https://pkg.go.dev/vuln/GO-2023-2186

chore: bump go version

---

pkg/go/transformer/dsltojson.go
pkg/go/transformer/jsontodsl.go
pkg/js/transformer/dsltojson.ts
pkg/js/transformer/jsontodsl.ts

This PR adds initial support for mixed operators to the Golang bindings.
Golang binding implementation for the initial mixed operators support as done in #107. Similar to the JS implementation, this change does not support anything involving multiple references to direct assignment, or the presence of direct assignment not as the first entry, or references to `self/this`.
- Golang implementation of JS bindings in #107 
- Closes #132

feat: add limited support for mixed operators in Golang binding

---

.github/workflows/main-js.yaml
pkg/js/Makefile
pkg/js/index.ts
pkg/js/package.json
pkg/js/transformer/dsltojson.ts
pkg/js/transformer/jsontodsl.ts
pkg/js/util/exceptions.ts
pkg/js/validator/validate-dsl.ts

Currently we're not running eslint on any files, this changes that and fixes any issues that arise.
It also proposes a new structure for the make commands in JS:
* `make lint` - runs `npm run lint` and `npm run format:check`, both will run even if the other fails. This is now used in CI to check that there are no lint errors and no formatting issues
* `make format` runs `npm run lint:fix` and `npm run format:fix`, both will run even if the other fails. This is most likely best used locally on a dev machine to have eslint/prettier fix what they can and then we review what's left.
I leaned on the side of removing code rather than disabling rules, but happy to revert some changes if desired.

chore(js): fix eslint warnings

---

.github/workflows/main-go.yaml
pkg/go/go.mod

Now that 1.22 is out in theory we can bump this, it should fix the golangci-lint issues that we're seeing due to their minimum version being bumped
Alternatively, we could
* pin to a version of `golangci-lint` other than latest
* match how CI works for JS and run our vulncheck and linting on a newer version of Go and then run tests using all our supported versions of Go rather than pointing to the go.mod file.
Edit:
I had to move this to `1.21.3` due to this being the version set in https://github.com/openfga/api/blob/main/proto/go.mod and go was enforcing that be set rather than `1.21`

chore: bump go version to 1.21

---

pkg/go/.golangci.yaml
pkg/go/transformer/mod-to-json.go
pkg/go/transformer/mod-to-json_test.go
pkg/go/transformer/testcases_test.go
pkg/js/errors.ts
pkg/js/package-lock.json
pkg/js/package.json
pkg/js/tests/_testcases.ts
pkg/js/tests/modules/mod-to-json.test.ts
pkg/js/transformer/modules/mod-to-json.ts
tests/data/fga-mod-transformer-cases.yaml

Adds test cases for transforming and validating an `fga.mod` file and then implements the function for JS. Currently working on Go and will move to ready once completed. Just putting up the PR now to get a review of the JS side ahead of then.
The `transformModFileToJSON` function will take a string representing a `fga.mod` file, parse it and then validate the fields inside. Given that this is isn't a complex file I've decided to just go checking ourselves rather than offloading onto a package like `ajv` to perform JSON Schema validation.
All error cases and messages are up for discussion, I'm not particularly married to them just tried to hit most I could think of.
I still need to add test cases for invalid yaml file (if that's possible to do inside our YAML test definition file 🤔  ) …

Implement transforming `fga.mod`

---

pkg/go/transformer/mod-to-json.go
pkg/go/transformer/mod-to-json_test.go
pkg/js/transformer/modules/mod-to-json.ts
tests/data/fga-mod-transformer-cases.yaml

Changes the return type of the `transformModFileToJSON` to a structure that allows us to return line and column information as part of the data to allow us to improve error reporting without tying us to the underlying yaml parser that we use on each platform.
Currently only has the JS implementation and will follow up with the Go implementation.
Resolves #173

feat: change transformModFileToJSON to return line and column information

---

pkg/go/transformer/mod-to-json.go
pkg/go/transformer/mod-to-json_test.go
pkg/js/transformer/modules/mod-to-json.ts
tests/data/fga-mod-transformer-cases.yaml

We initially added a `module` field to the `fga.mod` file, however after some thinking I'm proposing that we remove this field for the following:
* It doesn't actually do anything and can get erased as we never transfer it over to the transformed model (i.e.  a modular model is reconstructed from the JSON then it will be lost unlike schema version and contents).
* There doesn't seem to be (to me) a reason for it's existence, each module file will contain a module name and in the current iteration there doesn't seem to be any value to having a top-level module name. Whilst one might exist in the future I feel that attempting to design for that now might paint us into a corner as we do not know any future needs right now.

chore: remove module from fga.mod definition

---

.github/workflows/main-go.yaml
.github/workflows/main-js.yaml
pkg/go/transformer/module-to-model_test.go
pkg/go/transformer/testcases_test.go

The Go package currently doesn't have validation so we want to ignore those specific errors when running the modular transform tests, we can detect these by if they have `metadata.errorType` set so we filter them out when constructing out test case.
Also corrects the `paths` used to include the `**` so that changes under tests will trigger the JS and Go tests to run even if the source files aren't touched

chore(go): filter out validation errors when constructing go testcases

---

pkg/go/transformer/module-to-model.go
pkg/go/transformer/module-to-model_test.go
pkg/js/tests/modules/module-to-model.test.ts
pkg/js/transformer/modules/modules-to-model.ts

Adds support for passing the schema version when transforming a modular model.
Initially I was going to do this in an optional manner, but then realised that realistically anyone who is using this will always pass the schema version anyway so it made sense to move this to required and not have a default version.
Validation is left to the standard validation logic.
Closes #188

feat: allow passing a custom schema version to modular transform

---

pkg/go/transformer/module-to-model.go
pkg/go/transformer/module-to-model_test.go
pkg/go/transformer/testcases_test.go
pkg/js/tests/modules/module-to-model.test.ts
pkg/js/transformer/modules/modules-to-model.ts
tests/data/transformer-module/01-module-with-errors/expected_errors.json
tests/data/transformer-module/01-module-with-errors/module/syntax-error.fga

Adds a test for a DSL file with a syntax error and then ensure that we correctly return this as part of the overall modular model transform

chore: correctly handle syntax errors during parsing of the dsl

---

pkg/js/util/exceptions.ts
pkg/js/validator/validate-dsl.ts

This PR proposed moving the existing `exceptionCollector` function to be a class, we're already kind of mimicking this by returning an object with the functions attached but by moving to a class it means we can more easily type the `collector` we pass around and when refactoring we're able to get typing.

refactor(js): move exceptioncollector to be a class

---

pkg/java/src/main/java/dev/openfga/language/errors/ValidationError.java
pkg/java/src/main/java/dev/openfga/language/validation/DslValidator.java
pkg/java/src/main/java/dev/openfga/language/validation/InvalidChildRelationMetadata.java
pkg/java/src/main/java/dev/openfga/language/validation/ValidationErrorsBuilder.java

Implements the new `invalid-relation-on-tupleset` error for Java, this should fix the CI on the modular models branch
JS PR: #211

feat(java): implement invalid-relation-on-tupleset error

---

.github/workflows/main-go.yaml
.github/workflows/main-java.yml
.github/workflows/main-js.yaml

Corrects the `Build and Test (Java)` workflow to use the glob syntax to ensure any file under `tests` causes tests to run. Also corrects the `merge_group` usage to match the [docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group), it doesn't support paths, only an activity type.

ci: run java when test files change, correct merge_group usage

---

pkg/go/transformer/dsltojson.go
pkg/go/transformer/mod-to-json.go
pkg/go/utils/line-numbers.go
pkg/java/src/main/java/dev/openfga/language/OpenFgaDslErrorListener.java
pkg/java/src/main/java/dev/openfga/language/validation/ValidationErrorsBuilder.java
pkg/js/errors.ts
pkg/js/transformer/dsltojson.ts
pkg/js/transformer/modules/mod-to-json.ts
pkg/js/transformer/modules/modules-to-model.ts
pkg/js/util/exceptions.ts
tests/data/dsl-semantic-validation-cases.yaml
tests/data/dsl-syntax-validation-cases.yaml
tests/data/fga-mod-transformer-cases.yaml
tests/data/transformer-module/01-module-with-errors/expected_errors.json
tests/data/transformer-module/03-module-with-more-errors/expected_errors.json
tests/data/transformer-module/04-module-with-even-more-errors/expected_errors.json
tests/data/transformer-module/05-module-with-relation-errors/expected_errors.json

Makes the line and column numbers for the various errors 0 based, we were mostly 1 based already with the exception of some oversights (Go default error in some modular cases) and the line (but not column) on syntax errors from antlr.
This is separated into different commits for the tests and each language to help with review. There is a little bit of awkwardness in that we don't assert the errors in Go and Java due to differences in the errors across languages, but it shouldn't be an issue.

Make line and column numbers zero based

---

pkg/js/tests/modules/module-to-model.test.ts
pkg/js/transformer/modules/modules-to-model.ts
pkg/js/util/exceptions.ts
pkg/js/validator/validate-dsl.ts
tests/data/transformer-module/01-module-with-errors/expected_errors.json
tests/data/transformer-module/01-module-with-errors/module/org.fga

Introduces more tests for `transformModuleFilesToModel` by running the existing semantic validation suite against it by slightly editing the DSL and using as a single file module.
* 62c656dbaad0798de64947331ac4f8e0f20a4c6a - Sets up the testing
* 9dd3d63d512bf56a976fbc3b0ff7572c9501a2eb - Copies the fix from #219
* 7c1e36ce2c9cf92ea69fe33aeeb96fc30e8a5c0f - Handles the missed duplicates errors as this was already being handled by the code in `transformModuleFilesToModel`, I've removed this from the transform code and instead we're mapping the errors from the validate function as I think realistically we want to try and perform as little validation in transform as possible.

Run semantic validation test cases against transformModuleFilesToModel 

---

pkg/js/transformer/modules/modules-to-model.ts
pkg/js/validator/validate-dsl.ts

Fixes the circular dependency being raised by the new release of madge
See https://github.com/openfga/language/actions/runs/8612056598/job/23604058708?pr=228

fix(js): remove circular dependency

---

pkg/java/src/main/java/dev/openfga/language/OpenFgaDslListener.java

Fixes lint error from PR before we added Java linting

chore(java): fix lint error

---

pkg/java/build.gradle
pkg/java/src/main/java/dev/openfga/language/FgaModFile.java
pkg/java/src/main/java/dev/openfga/language/FgaModTransformer.java
pkg/java/src/main/java/dev/openfga/language/ModFileArrayProperty.java
pkg/java/src/main/java/dev/openfga/language/ModFileStringProperty.java
pkg/java/src/main/java/dev/openfga/language/errors/ModFileValidationError.java
pkg/java/src/main/java/dev/openfga/language/errors/ModFileValidationSingleError.java
pkg/java/src/test/java/dev/openfga/language/FgaModToJsonShould.java
pkg/java/src/test/java/dev/openfga/language/util/FgaModTestCase.java
pkg/java/src/test/java/dev/openfga/language/util/TestsData.java

Implements `fga.mod` transformation for the Java package, the yaml handling is done using the Jackson library that was already being used for tests. I evaluated some of the other libraries mentioned on the [yaml site](https://yaml.org) but they either proved too low level (snakeYAML) or didn't provide the functionality we needed (the rest).

feat(java): implement fga.mod transformer

---

.github/workflows/main-go.yaml
.github/workflows/main-java.yml
.github/workflows/main-js.yaml

I forgot to remove the CI setup for the modular models feature branch at merge, so remove that and also fix the `paths` value in the java workflow as it currently wont run if we edit the tests due to a missing quote

ci: remove feature branch and fix path on java pr target

---

pkg/java/src/main/java/dev/openfga/language/validation/ValidationOptions.java
pkg/js/package-lock.json
pkg/js/package.json
pkg/js/tests/_testcases.ts
pkg/js/tests/valdiate-store.test.ts
pkg/js/tests/validate-rules.test.ts
pkg/js/validator/validate-dsl.ts
pkg/js/validator/validate-rules.ts
pkg/js/validator/validate-store.ts
tests/data/dsl-semantic-validation-cases.yaml
tests/data/stores/00-valid-model/store.fga.yaml
tests/data/stores/01-valid-model-file/model.fga
tests/data/stores/01-valid-model-file/store.fga.yaml
tests/data/stores/02-missing-model/expected_errors.json
tests/data/stores/02-missing-model/store.fga.yaml
tests/data/stores/03-additional-properties/expected_errors.json
tests/data/stores/03-additional-properties/store.fga.yaml
tests/data/transformer-module/01-module-with-errors/expected_errors.json

- closes https://github.com/openfga/language/issues/278

chore: moved store validation to language

---

pkg/java/src/main/java/dev/openfga/language/validation/ValidationErrorsBuilder.java
pkg/js/transformer/modules/modules-to-model.ts
pkg/js/util/exceptions.ts
pkg/js/validator/validate-dsl.ts
tests/data/dsl-semantic-validation-cases.yaml

* Added tests from API
* Cycle tests are currently skipped
* Fix `InvalidType` exception when type & relation name. `InvalidType` now only marks the type on the right side of a relation definition
* refactor `hasEntryPointOrLoop` to return objects, not arrays
* https://github.com/openfga/language/issues/181
* https://github.com/openfga/language/issues/259

chore: migrating server tests

---

pkg/java/src/main/java/dev/openfga/language/OpenFgaDslErrorListener.java

This bug when uncaught because it is a wrapped ANTLR error and the line & col number are not compared as part of the tests.
https://github.com/openfga/language/blob/2663f80f254c099b7d588890587880da530b70e8/pkg/java/src/test/java/dev/openfga/language/ModelValidatorShould.java#L39
- fixes https://github.com/openfga/language/issues/329

fix: java syntax errors have wrong line base

---

pkg/go/utils/model_utils.go
pkg/go/utils/model_utils_test.go
pkg/java/src/main/java/dev/openfga/language/utils/ModelUtils.java
pkg/java/src/test/java/dev/openfga/language/utils/ModelUtilsTest.java
pkg/js/util/model_utils.test.ts
pkg/js/util/model_utils.ts

This adds two methods:
* `GetModuleForObjectTypeRelation`: returns the module for a specific type / relation
* `IsRelationAssignable`: returns whether a relation is assignable or not

feat: add method to get module for a relation & check if rel assignable

---

pkg/go/CHANGELOG.md
pkg/java/CHANGELOG.md
pkg/java/publish.gradle
pkg/js/CHANGELOG.md
pkg/js/package-lock.json
pkg/js/package.json

* **Go**: `v0.2.0-beta.1`
Added:
- Add `getModuleForObjectTypeRelation` utility method (#336)
- Add `isRelationAssignable` utility method (#336)
- Add utility validators for tuple fields and condition names (#294)
- Add an initial implementation of a model graph (#307,#308,#309,#310,#316,#317,#321,#322,#330)
* **JS**: `v0.2.0-beta.20`
Added:
- Add `getModuleForObjectTypeRelation` utility method (#336)
- Add `isRelationAssignable` utility method (#336)
Fixed:
- correct reported location of errors in some cases (#127)
- `tupleuserset-not-direct` is now prioritized above `no-entrypoint` error (#314)
- condition name is now correctly restrict to 50 characters (#320)
* **Java**: `v0.2.0-beta.2`
Added:
- Add `getModuleForObjectTypeRelation` utility method (#336)
- Add `isRelationAssignable` …

release: release new versions of go, js and java

---

pkg/go/CHANGELOG.md
pkg/js/CHANGELOG.md
pkg/js/package-lock.json
pkg/js/package.json

New releases to fix the issue with the generated code

release: js and go changelog entries

---

pkg/go/CHANGELOG.md
pkg/js/CHANGELOG.md

Didn't update when copy pasting the new version

docs: fix headers for latest releases

---

pkg/go/graph/graph.go
pkg/go/graph/graph_builder.go
pkg/go/graph/graph_builder_test.go
pkg/go/graph/graph_test.go

Add ability to visualize and represent graphs like this (the direction of a Check API request)
in addition to this (the direction of a ListObjects API request)

feat: add Reversed method to graph

---

pkg/go/graph/graph_edge.go

Allow query on edge type.  Also optimize Edge.Attributes

feat: allow query on edge type

---

.github/CODEOWNERS

Add backend team as codeowner of pkg/go/graph

chore: add backend as codeowners of graph

---

pkg/go/graph/graph_builder.go
pkg/go/graph/graph_node.go
pkg/go/graph/graph_test.go

Address linter complaint: https://github.com/openfga/language/actions/runs/11024544895/job/30617891293?pr=351#step:5:871
```
Error: graph/graph_builder.go:94:14: string `union` has 3 occurrences, make it a constant (goconst)
operator = "union"
^
make[1]: *** [Makefile:41: lint] Error 1
make[1]: Leaving directory '/home/runner/work/language/language
```

chore: introduce constant for operators

---

pkg/go/transformer/module-to-model.go
pkg/js/transformer/modules/modules-to-model.ts
tests/data/transformer-module/01-module-with-errors/expected_errors.json
tests/data/transformer-module/01-module-with-errors/module/nomodule.fga

The change checks the metadata for the module, if it's null it returns the proper error.
Fixes https://github.com/openfga/language/issues/384

fix: resolve crash in `TransformModuleFilesToModel` if regular schema file passed instead

---

pkg/go/graph/graph.go
pkg/go/graph/graph_builder.go
pkg/go/graph/weighted_graph_builder_test.go

feedback from github.com/openfga/language/pull/422
- Added more assertions to the condition tests
- AddEdge to accept slice of conditions
- Added more comments to better understand the algorithm changes.
-

feedback from github.com/openfga/language/pull/422

---

pkg/go/graph/weighted_graph.go
pkg/go/graph/weighted_graph_builder_test.go
pkg/go/graph/weighted_graph_test.go

For relation A but not B, we need to use a mixed strategy in calculating weight where a type in A will use the max strategy and B will use the enforced type strategy. This is because a type can be connected to the graph if it appears only in A as B is not mandatory.  However, a type listed in B MUST also appear in A.  Otherwise, relation will never exist for such type.

fix: exclusion weight where type is not in the excluded relation

---

.github/workflows/pkg-js-build.yaml

Aligns the JS workflow with Go/Java to only run `make test-js`, this is so that don't run any linting which reduces the chance of hitting errors with supporting older node versions (like in https://github.com/openfga/language/pull/462)

ci(js): only run tests per node version

---

.github/workflows/pkg-java-pr.yaml

Potential fix for [https://github.com/openfga/language/security/code-scanning/6](https://github.com/openfga/language/security/code-scanning/6)
To fix the problem, we should add a `permissions` block to the workflow file `.github/workflows/pkg-java-pr.yaml`. This block should be placed at the top level (applies to all jobs unless overridden), or at the job level if different jobs require different permissions. Since the job here is simply calling a reusable workflow and there is no evidence of needing write access, we should set the permissions to the minimal required, typically `contents: read`. If the workflow needs to create or update pull requests, we can add `pull-requests: write`. However, as a minimal starting point, we will set `contents: read` at the workflow level, which is the …

Potential fix for code scanning alert no. 6: Workflow does not contain permissions

---

.github/workflows/pkg-go-build.yaml

Potential fix for [https://github.com/openfga/language/security/code-scanning/4](https://github.com/openfga/language/security/code-scanning/4)
To fix the problem, explicitly set the `permissions` key at the top level of the workflow file. This will apply the specified permissions to all jobs in the workflow unless overridden at the job level. Since the jobs in this workflow only check out code, set up Go, lint, audit, and build/test, the minimal required permission is `contents: read`. This ensures the workflow adheres to the principle of least privilege and prevents the `GITHUB_TOKEN` from having unnecessary write access. The change should be made by adding the following block after the `name:` and before the `on:` key in `.github/workflows/pkg-go-build.yaml`.
---
_Suggested fixes …

Potential fix for code scanning alert no. 4: Workflow does not contain permissions

---

.github/workflows/pkg-go-release.yaml

Potential fix for [https://github.com/openfga/language/security/code-scanning/2](https://github.com/openfga/language/security/code-scanning/2)
To fix the problem, add a `permissions` block to the `test` job in `.github/workflows/pkg-go-release.yaml`. The minimal and safest default is `contents: read`, which allows the job to read repository contents but not write or perform other privileged actions. This should be added at the same indentation level as `uses` and `secrets` under the `test` job. No other changes are needed, and this does not affect existing functionality.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 2: Workflow does not contain permissions

---

.github/workflows/pkg-go-build.yaml

Potential fix for [https://github.com/openfga/language/security/code-scanning/1](https://github.com/openfga/language/security/code-scanning/1)
To fix the problem, add a `permissions` block to the workflow file to explicitly set the minimum required permissions for the `GITHUB_TOKEN`. Since the jobs in this workflow only need to check out code and run local commands (lint, build, audit), the minimal required permission is `contents: read`. This can be set at the top level of the workflow file, which will apply to all jobs unless overridden. No changes to the jobs themselves are needed.
**Steps:**
- Add the following block after the `name:` line and before the `on:` block in `.github/workflows/pkg-go-build.yaml`:
```yaml
permissions:
contents: read
```
- No additional imports, methods, or …

Potential fix for code scanning alert no. 1: Workflow does not contain permissions

---

.github/workflows/pkg-js-release.yaml

Potential fix for [https://github.com/openfga/language/security/code-scanning/9](https://github.com/openfga/language/security/code-scanning/9)
To fix the problem, add a `permissions` block to the `test` job in `.github/workflows/pkg-js-release.yaml`. The minimal and safest starting point is to set `permissions: {}` (no permissions), unless the reusable workflow requires specific permissions. If the reusable workflow only needs read access to the repository contents (which is common for test/build jobs), set `permissions: contents: read`. This change should be made directly under the `test:` job definition, before `uses:`. No other changes are required.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 9: Workflow does not contain permissions
